FROM oven/bun:1.2.21-alpine
WORKDIR /var/www/bytecamp-server

COPY ./backend/package.json ./package.json
COPY ./backend/bun.lock ./bun.lock

COPY ./backend ./

# Install all workspace deps
RUN bun install --lockfile

WORKDIR /var/www/bytecamp-server
EXPOSE 3000

CMD ["bun", "run", "src/index.ts"]